import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Float, DateTime,
    ForeignKey, JSON, Text, Enum, Integer
)
from sqlalchemy.orm import relationship

from ..extensions import db
from .quiz_session import VARK_STYLE_ENUM


def _uuid():
    return str(uuid.uuid4())


def _now():
    return datetime.now(timezone.utc)


CLASSIFIER_VERSION_ENUM = Enum(
    "rule_based",    # Sprint 4 – deterministic scoring matrix
    "xgboost_v1",    # Sprint 7 – XGBoost trained model
    "rf_v1",         # Sprint 7 – Random Forest alternative
    name="classifier_version_enum",
    create_type=True,
)


class VarkProfile(db.Model):
    """
    VARK classification result for one completed QuizSession.

    One session → one VarkProfile (1-to-1 via session_id unique constraint).
    Users accumulate many VarkProfiles over time; the history is shown on
    ProfilePage as a radar / line evolution chart.

    Score semantics
    ---------------
    v_score, a_score, r_score, k_score are raw scores produced by the
    classifier (rule-based: weighted feature sum; ML: class probability).
    They do NOT need to sum to 1.0 — normalise at display time.
    dominant_style is the argmax of the four raw scores.

    Feature snapshot
    ----------------
    raw_features stores the exact signal vector fed to the classifier so we
    can retrain / audit without re-running the quiz.
    """
    __tablename__ = "vark_profiles"

    # ── Primary key ───────────────────────────────────────────────────────────
    id = Column(String(36), primary_key=True, default=_uuid)

    # ── Foreign keys ──────────────────────────────────────────────────────────
    user_id    = Column(
        String(36), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    session_id = Column(
        String(36), ForeignKey("quiz_sessions.id", ondelete="CASCADE"),
        nullable=False, unique=True, index=True,   # one profile per session
    )

    # ── VARK scores ───────────────────────────────────────────────────────────
    v_score = Column(Float, nullable=False, default=0.0)   # Visual
    a_score = Column(Float, nullable=False, default=0.0)   # Auditory
    r_score = Column(Float, nullable=False, default=0.0)   # Reading / Writing
    k_score = Column(Float, nullable=False, default=0.0)   # Kinesthetic

    dominant_style = Column(VARK_STYLE_ENUM, nullable=False)

    # ── Classifier metadata ───────────────────────────────────────────────────
    classifier_version = Column(
        CLASSIFIER_VERSION_ENUM, nullable=False, default="rule_based"
    )
    classifier_confidence = Column(Float, nullable=True)   # max(scores) / sum(scores)
    model_version_tag     = Column(String(64), nullable=True)  # e.g. "xgb-2025-08-01"

    # ── Raw feature snapshot ──────────────────────────────────────────────────
    # {
    #   "mcq_accuracy":       0.72,
    #   "theory_accuracy":    0.50,
    #   "coding_accuracy":    0.33,
    #   "avg_time_ms":        18200,
    #   "skip_ratio":         0.10,
    #   "fast_answer_ratio":  0.40,   # answered in <10 s
    #   "hint_used_ratio":    0.05,
    #   "answer_change_ratio":0.20,
    #   "tab_switch_ratio":   0.00,
    #   "total_questions":    20,
    # }
    raw_features = Column(JSON, nullable=True)

    # ── Human-readable summary generated by LLM after classification ─────────
    style_summary     = Column(Text, nullable=True)   # 2–3 sentence plain-English summary
    study_tips        = Column(JSON, nullable=True)   # list[str] – actionable recommendations

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at = Column(DateTime(timezone=True), default=_now, nullable=False)

    # ── Relationships ─────────────────────────────────────────────────────────
    user    = relationship("User",        back_populates="vark_profiles")
    session = relationship("QuizSession", back_populates="vark_profiles")

    # ── Helpers ───────────────────────────────────────────────────────────────
    @property
    def scores_dict(self) -> dict:
        return {
            "visual":      self.v_score,
            "auditory":    self.a_score,
            "reading":     self.r_score,
            "kinesthetic": self.k_score,
        }

    @property
    def normalised_scores(self) -> dict:
        """Return scores as percentages (sum = 100)."""
        total = self.v_score + self.a_score + self.r_score + self.k_score
        if total == 0:
            return {"visual": 0, "auditory": 0, "reading": 0, "kinesthetic": 0}
        return {
            "visual":      round(self.v_score / total * 100, 1),
            "auditory":    round(self.a_score / total * 100, 1),
            "reading":     round(self.r_score / total * 100, 1),
            "kinesthetic": round(self.k_score / total * 100, 1),
        }

    @classmethod
    def from_scores(
        cls,
        user_id: str,
        session_id: str,
        v: float, a: float, r: float, k: float,
        classifier_version: str = "rule_based",
        raw_features: dict | None = None,
        model_version_tag: str | None = None,
    ) -> "VarkProfile":
        """Factory — picks dominant_style automatically."""
        scores = {"visual": v, "auditory": a, "reading": r, "kinesthetic": k}
        dominant = max(scores, key=scores.get)
        total    = v + a + r + k
        confidence = scores[dominant] / total if total > 0 else None
        return cls(
            user_id=user_id,
            session_id=session_id,
            v_score=v, a_score=a, r_score=r, k_score=k,
            dominant_style=dominant,
            classifier_version=classifier_version,
            classifier_confidence=confidence,
            model_version_tag=model_version_tag,
            raw_features=raw_features,
        )

    # ── Serialisation ─────────────────────────────────────────────────────────
    def to_dict(self, include_features: bool = False) -> dict:
        data = {
            "id":                     self.id,
            "user_id":                self.user_id,
            "session_id":             self.session_id,
            # raw scores
            "v_score":                self.v_score,
            "a_score":                self.a_score,
            "r_score":                self.r_score,
            "k_score":                self.k_score,
            # derived
            "dominant_style":         self.dominant_style,
            "normalised_scores":      self.normalised_scores,
            "classifier_confidence":  self.classifier_confidence,
            # classifier provenance
            "classifier_version":     self.classifier_version,
            "model_version_tag":      self.model_version_tag,
            # human-readable output
            "style_summary":          self.style_summary,
            "study_tips":             self.study_tips,
            # timestamp
            "created_at":             self.created_at.isoformat(),
        }
        if include_features:
            data["raw_features"] = self.raw_features
        return data

    def __repr__(self) -> str:
        return (
            f"<VarkProfile {self.id[:8]} "
            f"dominant={self.dominant_style} "
            f"conf={self.classifier_confidence:.2f if self.classifier_confidence else 'N/A'}>"
        )