"""
migrations/env.py
-----------------
Alembic environment script.
Auto-generated by `flask db init`, then extended to:
  - Import all SQLAlchemy models so Alembic sees the full schema
  - Support both online (live DB) and offline (SQL script) migration modes
  - Read the database URL from Flask app config so a single .env drives everything
"""

from __future__ import annotations

import logging
import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make the project root importable when running `alembic` directly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# ---------------------------------------------------------------------------
# Alembic Config object (gives access to values in alembic.ini)
# ---------------------------------------------------------------------------
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# ---------------------------------------------------------------------------
# Import Flask app & models so metadata is populated
# ---------------------------------------------------------------------------
from app import create_app                      # noqa: E402
from app.extensions import db                   # noqa: E402

# Import ALL models here so Alembic can detect additions/removals/changes.
from app.models.user         import User        # noqa: F401, E402
from app.models.quiz_session import QuizSession # noqa: F401, E402
from app.models.question     import Question    # noqa: F401, E402
from app.models.response     import Response    # noqa: F401, E402
from app.models.vark_profile import VarkProfile # noqa: F401, E402

flask_app = create_app(os.getenv("APP_ENV", "development"))
target_metadata = db.metadata

# Override sqlalchemy.url from Flask config so alembic.ini doesn't need it
config.set_main_option(
    "sqlalchemy.url",
    flask_app.config["SQLALCHEMY_DATABASE_URI"].replace("%", "%%"),
)


# ---------------------------------------------------------------------------
# Offline mode — generate a .sql script without a live DB connection
# ---------------------------------------------------------------------------

def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.
    Useful for generating migration SQL to review before applying.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url                     = url,
        target_metadata         = target_metadata,
        literal_binds           = True,
        dialect_opts            = {"paramstyle": "named"},
        compare_type            = True,   # detect column-type changes
        compare_server_default  = True,
    )

    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online mode — apply migrations against a live DB connection
# ---------------------------------------------------------------------------

def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode against the configured database.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix      = "sqlalchemy.",
        poolclass   = pool.NullPool,   # no persistent pool in migration scripts
    )

    with connectable.connect() as connection:
        context.configure(
            connection              = connection,
            target_metadata         = target_metadata,
            compare_type            = True,
            compare_server_default  = True,
            include_schemas         = True,
        )

        with context.begin_transaction():
            context.run_migrations()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if context.is_offline_mode():
    logger.info("Running migrations in offline mode.")
    run_migrations_offline()
else:
    logger.info("Running migrations in online mode.")
    with flask_app.app_context():
        run_migrations_online()